const product = [
  {
    id: 1,
    title: 'ADIDAS BY STELLA MCCARTNEY ULTRABOOST SPEED',
    price: '$280',
    imgSrc: [
      'img/imgIn/ADIDAS BY STELLA MCCARTNEY ULTRABOOST SPEED/i-main.avif',
      'img/imgIn/ADIDAS BY STELLA MCCARTNEY ULTRABOOST SPEED/i-1.avif',
      'img/imgIn/ADIDAS BY STELLA MCCARTNEY ULTRABOOST SPEED/i-2.avif',
      'img/imgIn/ADIDAS BY STELLA MCCARTNEY ULTRABOOST SPEED/i-3.avif',
      'img/imgIn/ADIDAS BY STELLA MCCARTNEY ULTRABOOST SPEED/i-4.avif',
      'img/imgIn/ADIDAS BY STELLA MCCARTNEY ULTRABOOST SPEED/i-bag.avif',
    ],
    colors: '2 colors available',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 2,
    title: 'AVRYN SHOES',
    price: '$140',
    imgSrc: [
      'img/imgIn/AVRYN SHOES/i-main.avif',
      'img/imgIn/AVRYN SHOES/i-2.avif',
      'img/imgIn/AVRYN SHOES/i-1.avif',
      'img/imgIn/AVRYN SHOES/i-3.avif',
      'img/imgIn/AVRYN SHOES/i-4.avif',
      'img/imgIn/AVRYN SHOES/i-bag.avif',
    ],
    colors: '11 colors available',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 3,
    title: 'FORUM 84 LOW ADV SHOES',
    price: '$110',
    imgSrc: [
      'img/imgIn/FORUM 84 LOW ADV SHOES/i-main.avif',
      'img/imgIn/FORUM 84 LOW ADV SHOES/i-1.avif',
      'img/imgIn/FORUM 84 LOW ADV SHOES/i-2.avif',
      'img/imgIn/FORUM 84 LOW ADV SHOES/i-3.avif',
      'img/imgIn/FORUM 84 LOW ADV SHOES/i-4.avif',
      'img/imgIn/FORUM 84 LOW ADV SHOES/i-bag.avif',
    ],
    colors: '4 colors available',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 4,
    title: 'NMD S1 SHOES',
    price: '$200',
    imgSrc: [
      'img/imgIn/NMD_S1 SHOES/i-main.avif',
      'img/imgIn/NMD_S1 SHOES/i-1.avif',
      'img/imgIn/NMD_S1 SHOES/i-2.avif',
      'img/imgIn/NMD_S1 SHOES/i-3.avif',
      'img/imgIn/NMD_S1 SHOES/i-4.avif',
      'img/imgIn/NMD_S1 SHOES/i-bag.avif',
    ],
    colors: '8 colors available',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 5,
    title: 'SAMBA OG SHOES',
    price: '$100',
    imgSrc: [
      'img/imgIn/SAMBA OG SHOES/i-main.avif',
      'img/imgIn/SAMBA OG SHOES/i-1.avif',
      'img/imgIn/SAMBA OG SHOES/i-2.avif',
      'img/imgIn/SAMBA OG SHOES/i-3.avif',
      'img/imgIn/SAMBA OG SHOES/i-4.avif',
      'img/imgIn/SAMBA OG SHOES/i-bag.avif',
    ],
    colors: '6 colors available',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 6,
    title: 'SUPERSTAR XLG SHOES',
    price: '$110',
    imgSrc: [
      'img/imgIn/SUPERSTAR XLG SHOES/i-main.avif',
      'img/imgIn/SUPERSTAR XLG SHOES/i-1.avif',
      'img/imgIn/SUPERSTAR XLG SHOES/i-2.avif',
      'img/imgIn/SUPERSTAR XLG SHOES/i-3.avif',
      'img/imgIn/SUPERSTAR XLG SHOES/i-4.avif',
      'img/imgIn/SUPERSTAR XLG SHOES/i-bag.avif',
    ],
    colors: '5 colors available',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 7,
    title: 'TERREX AX4 GORE-TEX HIKING SHOES',
    price: '$120',
    imgSrc: [
      'img/imgIn/TERREX AX4 GORE-TEX HIKING SHOES/i-main.avif',
      'img/imgIn/TERREX AX4 GORE-TEX HIKING SHOES/i-1.avif',
      'img/imgIn/TERREX AX4 GORE-TEX HIKING SHOES/i-2.avif',
      'img/imgIn/TERREX AX4 GORE-TEX HIKING SHOES/i-3.avif',
      'img/imgIn/TERREX AX4 GORE-TEX HIKING SHOES/i-4.avif',
      'img/imgIn/TERREX AX4 GORE-TEX HIKING SHOES/i-bag.avif',
    ],
    colors: '11 colors available',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
  {
    id: 8,
    title: 'TYSHAWN REMASTERED SHOES',
    price: '$85',
    imgSrc: [
      'img/imgIn/TYSHAWN REMASTERED SHOES/i-main.avif',
      'img/imgIn/TYSHAWN REMASTERED SHOES/i-1.avif',
      'img/imgIn/TYSHAWN REMASTERED SHOES/i-2.avif',
      'img/imgIn/TYSHAWN REMASTERED SHOES/i-3.avif',
      'img/imgIn/TYSHAWN REMASTERED SHOES/i-4.avif',
      'img/imgIn/TYSHAWN REMASTERED SHOES/i-bag.avif',
    ],
    colors: '7 colors available',
    size: 11,
    count: 1,
    inBag: false,
    liked: false,
  },
]
